server:
  port: ${PORT}

  cloud:
    config:
      server:
        git:
          uri: https://github.com/MiguelVMR/ead-config-server-repo
          username: ${USERNAME_GITHUB}
          password: ${TOKEN_GITHUB}

encrypt:
  key: ${KEY}

ead:
  configServer:
    username: ${CONFIG_SERVER_USERNAME}
    password: '${CONFIG_SERVER_PASSWORD}'

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80
