server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MiguelVMR/ead-config-server-repo
          username: ${USERNAME_GITHUB}
          password: ${TOKEN_GITHUB}


eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
